bosh-uuid: ac3304f5-908a-446e-8b88-5a81ed349298
release-name: sample-boshrelease
stemcell-alias: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
vm-type: t2-micro
az-name: us-east-1c
network-name: infra
job-name: sample
listen-port: 8080
