releases:
- name: ((release-name))
  version: ((release-version))
addons:
- name: ((release-name))-demo
  jobs:
  - name: ((job-name))
    release: ((release-name))
    properties:
      listen_port: 0
  include:
    deployments:
    - ((deployment-name))
